name: build-tool-docker

on:
  workflow_call:
    inputs:
      TOOL:
        type: string
        required: true
      VERSION:
        type: string
        required: true
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

defaults:
  run:
    shell: bash

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: ${{ inputs.TOOL }}/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ vars.DOCKERHUB_USERNAME }}/spotify-${{ inputs.TOOL }}:${{ inputs.VERSION }}
