name: pr

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

defaults:
  run:
    shell: bash

jobs:

  checks:
    uses: ./.github/workflows/checks.yml
    secrets: inherit

  build-tools:
    uses: ./.github/workflows/build-tools.yml
    with:
      VERSION: ${{ github.sha }}
    secrets: inherit
