name: tag-and-release

on:
  push:
    branches:
      - main

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:

  tag-and-release:
    uses: lucaspopp0/workflows/.github/workflows/tag-and-release.yml@v1

  release-tools:
    needs: [tag-and-release]
    uses: ./.github/workflows/release-tools.yml
    with:
      VERSION: ${{ needs.tag-and-release.outputs.version }}
    secrets: inherit
