name: docker-build-and-push

on:
  workflow_call:
    inputs:
      TOOL:
        type: string
        required: true
      VERSION:
        type: string
        required: true
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

defaults:
  run:
    shell: bash

jobs:

  docker-build-and-push:
    name: docker-build-and-push (${{ inputs.TOOL }})
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/spotify-${{ inputs.TOOL }}
          tags: |
            type=ref,event=pr
            type=semver,pattern={{version}},value=${{ inputs.VERSION }}
            type=semver,pattern={{major}}.{{minor}},value=${{ inputs.VERSION }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.TOOL }}
          file: ${{ inputs.TOOL }}/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64,linux/arm64/v8
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
